databases:
  - name: quizportal-db

services:
  - type: web
    name: quizportal-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput && python manage.py seed_quiz
    startCommand: gunicorn quiz_portal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quiz_portal.settings
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: quizportal-db
          property: connectionString